# Generated by Django 6.1.1 on 2026-10-01 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('agency_id', models.CharField(blank=True, max_length=50, null=True)),
                ('route_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('route_long_name', models.CharField(blank=True, max_length=255, null=True)),
                ('route_desc', models.TextField(blank=True, null=True)),
                ('route_type', models.IntegerField()),
                ('route_url', models.URLField(blank=True, null=True)),
                ('route_color', models.CharField(blank=True, max_length=10, null=True)),
                ('route_text_color', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stop_code', models.CharField(blank=True, max_length=50, null=True)),
                ('stop_name', models.CharField(max_length=255)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('stop_url', models.URLField(blank=True, null=True)),
                ('wheelchair_boarding', models.IntegerField(blank=True, null=True)),
                ('location_type', models.IntegerField(blank=True, null=True)),
                ('parent_station', models.CharField(blank=True, max_length=50, null=True)),
                ('level_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(db_index=True, max_length=100)),
                ('shape_pt_lat', models.FloatField()),
                ('shape_pt_lon', models.FloatField()),
                ('shape_pt_sequence', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['shape_id'], name='app_shape_shape_i_e9ba5d_idx')],
                'unique_together': {('shape_id', 'shape_pt_sequence')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=50)),
                ('trip_headsign', models.CharField(blank=True, max_length=255, null=True)),
                ('direction_id', models.IntegerField(blank=True, null=True)),
                ('shape_id', models.CharField(blank=True, max_length=100, null=True)),
                ('trip_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('wheelchair_accessible', models.IntegerField(blank=True, null=True)),
                ('bikes_allowed', models.IntegerField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='app.route')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.CharField(max_length=20)),
                ('departure_time', models.CharField(max_length=20)),
                ('stop_sequence', models.IntegerField()),
                ('pickup_type', models.IntegerField(blank=True, null=True)),
                ('drop_off_type', models.IntegerField(blank=True, null=True)),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='app.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='app.trip')),
            ],
            options={
                'unique_together': {('trip', 'stop_sequence')},
            },
        ),
    ]
