# Generated by Django 6.1.1 on 2026-10-01 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='app.stop')),
            ],
            options={
                'indexes': [models.Index(fields=['hour'], name='app_passeng_hour_4d24cc_idx')],
                'unique_together': {('stop', 'hour')},
            },
        ),
    ]
